# Generated by Django 5.2.7 on 2025-12-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_alquileres', '0005_devolucion_chofer_devolucion_entrega_and_more'),
        ('api_mantenimiento', '0001_initial'),
        ('api_notificaciones', '0002_notificacion_completada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_alquileres.entrega'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='mantenimiento_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_mantenimiento.mantenimientoproducto'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='retiro_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_alquileres.retirocliente'),
        ),
    ]
