# Generated by Django 5.2.7 on 2025-12-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_notificaciones', '0003_notificacion_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_realizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
