# Generated by Django 5.2.7 on 2025-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('USO', 'En uso'), ('MANTENIMIENTO', 'En mantenimiento'), ('FUERA', 'Fuera de servicio')], default='DISPONIBLE', max_length=15)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
