# Generated by Django 5.2.7 on 2025-11-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='email',
        ),
    ]
