# Generated by Django 5.2.7 on 2025-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_clientes', '0002_rename_correo_cliente_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='primer_apellido',
        ),
        migrations.AddField(
            model_name='cliente',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
