# Generated by Django 5.2.7 on 2025-11-20 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_inventario', '0001_initial'),
        ('api_productos', '0002_remove_producto_imagen_file_producto_imagen'),
        ('api_vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de mantenimiento',
                'verbose_name_plural': 'Tipos de mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='MantenimientoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_productos.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_mantenimiento.tipomantenimiento')),
            ],
            options={
                'verbose_name': 'Mantenimiento del producto',
                'verbose_name_plural': 'Mantenimiento de los productos',
            },
        ),
        migrations.CreateModel(
            name='MantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_vehiculos.vehiculo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_mantenimiento.tipomantenimiento')),
            ],
            options={
                'verbose_name': 'Mantenimiento del vehículo',
                'verbose_name_plural': 'Mantenimiento de los vehículos',
            },
        ),
        migrations.CreateModel(
            name='MantenimientoPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_inventario.pieza')),
                ('mantenimiento_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_mantenimiento.mantenimientoproducto')),
                ('mantenimiento_vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_mantenimiento.mantenimientovehiculo')),
            ],
            options={
                'verbose_name': 'Repuesto usado',
                'verbose_name_plural': 'Repuestos usados',
            },
        ),
    ]
