# Generated by Django 5.2.7 on 2025-11-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Modalidad de producto',
                'verbose_name_plural': 'Modalidades de productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('precio_alquiler', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ALQUILADO', 'En alquiler'), ('REPARACIÓN', 'En reparación'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=15)),
                ('imagen_file', models.ImageField(blank=True, null=True, upload_to='Productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_productos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoModalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_productos.modalidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_productos.producto')),
            ],
            options={
                'verbose_name': 'Producto por Modalidad',
                'verbose_name_plural': 'Productos por Modalidad',
                'unique_together': {('producto', 'modalidad')},
            },
        ),
    ]
