# Generated by Django 5.2.7 on 2025-12-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_tipo',
            field=models.CharField(blank=True, choices=[('NINGUNO', 'Sin descuento'), ('PORCENTAJE', 'Porcentaje'), ('FIJO', 'Monto fijo')], default='NINGUNO', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_tipo',
            field=models.CharField(blank=True, choices=[('NINGUNO', 'Sin descuento'), ('PORCENTAJE', 'Porcentaje'), ('FIJO', 'Monto fijo')], default='NINGUNO', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
