# Generated by Django 5.2.7 on 2025-11-20 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_productos', '0002_remove_producto_imagen_file_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('minimo_stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_inventario.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inventario', to='api_productos.producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], default='ENTRADA', max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('despachador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MovimientoInventario', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MovimientoInventario', to='api_productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('PROVEEDOR', 'Proveedor'), ('RECUPERADO', 'Recuperado'), ('OTRO', 'Otro')], default='PROVEEDOR', max_length=15)),
                ('ubicacion', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('minimo_stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_inventario.bodega')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_inventario.pieza')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Inventario de pieza',
                'verbose_name_plural': 'Inventario de piezas',
            },
        ),
    ]
