# Generated by Django 5.2.7 on 2025-12-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventariopieza',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
