# Generated by Django 5.2.7 on 2025-12-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_inventario', '0002_remove_inventario_ubicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='stock',
            new_name='stock_disponible',
        ),
        migrations.AddField(
            model_name='inventario',
            name='stock_alquilado',
            field=models.IntegerField(default=0),
        ),
    ]
