# Generated by Django 5.2.7 on 2025-11-20 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_clientes', '0002_rename_correo_cliente_email'),
        ('api_productos', '0002_remove_producto_imagen_file_producto_imagen'),
        ('api_vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('contrato', models.URLField(blank=True, max_length=500, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_clientes.cliente')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
            },
        ),
        migrations.CreateModel(
            name='DetalleAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_alquileres.alquiler')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de la alquiler',
                'verbose_name_plural': 'Detalles de las alquileres',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('DAÑADO', 'Dañado'), ('REPARAR', 'Requiere reparación')], default='BUENO', max_length=10)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_alquileres.alquiler')),
            ],
            options={
                'verbose_name': 'Devoluvión',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('fecha_retorno', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RUTA', 'En ruta'), ('COMPLETADA', 'Completada'), ('DEVUELTA', 'Devuelta'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_alquileres.alquiler')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_vehiculos.vehiculo')),
            ],
        ),
    ]
