# Generated by Django 5.2.7 on 2025-12-09 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_alquileres', '0002_alquiler_descuento_tipo_alquiler_descuento_valor_and_more'),
        ('api_clientes', '0003_rename_apellido_cliente_primer_apellido_and_more'),
        ('api_ventas', '0002_detalleventa_descuento_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.CreateModel(
            name='RetiroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateTimeField(auto_now_add=True)),
                ('alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='api_alquileres.alquiler')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_clientes.cliente')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='api_ventas.venta')),
            ],
            options={
                'verbose_name': 'Retiro de Cliente',
                'verbose_name_plural': 'Retiros de Clientes',
            },
        ),
    ]
