# Generated by Django 5.2.7 on 2025-12-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_alquileres', '0003_alter_entrega_options_retirocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='contrato',
            field=models.TextField(blank=True, null=True),
        ),
    ]
