# Generated by Django 5.2.7 on 2025-12-12 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_alquileres', '0004_alter_alquiler_contrato'),
        ('api_vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='api_alquileres.entrega'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_vehiculos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='contrato',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_retorno',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_salida',
            field=models.DateTimeField(),
        ),
    ]
