# Generated by Django 5.2.7 on 2025-11-21 16:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('estado', models.CharField(choices=[('Presente', 'El empleado asistió normalmente a su jornada laboral.'), ('Ausente', 'El empleado no asistió y no presentó justificación válida.'), ('Justificado', 'El empleado no asistió, pero presentó una justificación(cita médica, incapacidad, permiso especial).'), ('Vacaciones', 'El empleado se encuentra en periodo de vacaciones autorizado'), ('Permiso', 'El empleado no asistió debido a un permiso aprobado(asuntos personales o familiares).')], default='Presente', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia registrada',
                'verbose_name_plural': 'Asistencias registradas',
            },
        ),
        migrations.CreateModel(
            name='ChoferDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia_numero', models.CharField(max_length=50)),
                ('licencia_tipo', models.CharField(choices=[('A1', 'Motocicleta hasta 125cc'), ('A2', 'Motocicleta de 126cc hasta 500cc'), ('B1', 'Vehículos liviano hasta 4000kg'), ('B2', 'Vehículos carga mediana (4000-8000kg)'), ('B3', 'Vehículos carga pesada (más de 8000kg)'), ('D1', 'Maquinaria liviana'), ('D2', 'Maquinaria mediana'), ('D3', 'Maquinaria pesada')], default='A1', max_length=3)),
                ('fecha_vencimiento', models.DateField()),
                ('experiencia_anios', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos de chofer',
                'verbose_name_plural': 'Datos de choferes',
            },
        ),
        migrations.CreateModel(
            name='DespachoDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos de despachador',
                'verbose_name_plural': 'Datos de despachadores',
            },
        ),
        migrations.CreateModel(
            name='MecanicoDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('certificaciones', models.TextField(blank=True, null=True)),
                ('experiencia_anios', models.IntegerField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos de mecanico',
                'verbose_name_plural': 'Datos de mecanicos',
            },
        ),
        migrations.CreateModel(
            name='RolesEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_responsabilidad', models.IntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto')], default=1)),
                ('requiere_licencia', models.BooleanField(default=False)),
                ('area_asignada', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_detail', to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol de Empleado',
                'verbose_name_plural': 'Roles de Empleados',
            },
        ),
    ]
