# Generated by Django 5.2.7 on 2025-11-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choferdatos',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='despachodatos',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='mecanicodatos',
            name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choferdatos',
            name='licencia_numero',
            field=models.CharField(max_length=20),
        ),
    ]
