# Generated by Django 5.2.7 on 2025-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_usuarios', '0002_remove_choferdatos_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
