# Generated by Django 5.2.7 on 2025-12-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_usuarios', '0004_alter_asistencia_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('Presente', 'El empleado asistió normalmente a su jornada laboral.'), ('Tarde', 'El empleado asistió pero llegó tarde.'), ('Ausente', 'El empleado no asistió y no presentó justificación válida.'), ('Justificado', 'El empleado no asistió, pero presentó una justificación(cita médica, incapacidad, permiso especial).'), ('Vacaciones', 'El empleado se encuentra en periodo de vacaciones autorizado'), ('Permiso', 'El empleado no asistió debido a un permiso aprobado(asuntos personales o familiares).')], default='Presente', max_length=20),
        ),
    ]
