# Generated by Django 5.2.7 on 2025-11-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_compras', '0001_initial'),
        ('api_inventario', '0001_initial'),
        ('api_productos', '0002_remove_producto_imagen_file_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_compras.ordencompra')),
                ('pieza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_inventario.pieza')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_productos.producto')),
            ],
        ),
    ]
